### ISSUE TITLE
Mac Sierra 10.12.3 not able to use the plugin.

### ISSUE THREAD

**Issue by setegonz** [blainesch/zazu-weather#1]
I installed it, and start typing the word weather and nothing happens, just show the option to search with google.

**Comment by bayleedev** [comment]
I'm also using Mac Sierra. I just did a clean install and it is working.

Can you upload the relevant log file in a gist? They are located in `~/.zazu/log`

**Comment by setegonz** [comment]
I just uninstalled and then reinstalled the plugin and now is working. Thank you.

**Comment by setegonz** [comment]
@blainesch I'm having the problem again. 
Here's the gist:
https://gist.github.com/setegonz/f76b61153576bc6746bd796f2de8399a

**Comment by bayleedev** [comment]
@setegonz there is some logic going out to make dependencies work better in the next zazu release.

I think I also have some ideas on making this repo not have dependencies, so this won't be such an issue.

**Comment by setegonz** [comment]
@blainesch Ok! I will wait for the next release. thanks.
